version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - laravel
    web:
        image: 'nginx:latest'
        ports:
            - '8080:80'
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_DATABASE: tm-test-db
            MYSQL_ROOT_PASSWORD: reallysecretpass
        networks:
            - laravel
    redis:
        image: 'redis:latest'
        networks:
            - laravel

networks:
    laravel:
